config/routes.rb
Rails.application.routes.draw do
  post '/products', to: 'products#create'
  get "/products/new", to: "products#new", as: :new_product
  get "/products", to: "products#index"
  get "/products/:id", to: "products#show", as: :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
@products = Product.all
end

def show 
@product = Product.find(params[:id])
end  

def new 
@product = Product.new
end   

def create
@product = Product.new(product_params) 

if @product.save
redirect_to products_path
else
render :new
end
end

private

def product_params
    params.require(:product).permit(:title, :description, :price)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=  render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Hola Mundo</h1>

<% @products.each do |product| %>
<%= link_to product_path(product.id), class: 'product' do %>
<h2><%= product.title %></h2>
<span><%= product.price %></span>
<% end %>
<% end %>

app/views/products/new.html.erb
<h2>Add product</h2>

<%= form_with model: @product do |form| %>
<div>
    <%= form.label :title %>
<%= form.text_field :title %>
</div>
<div>
    <%= form.label :description %>
    <%= form.text_area :description %>   
</div>
<div>
    <%= form.label :price %>
    <%= form.number_field :price %>   
</div>

<%= form.submit %>




<% end %>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %></h1>
<p class="description"><%= @product.description %></p>
<span class="price"><%= @product.price %> </span>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
<h1>Ecommerce APP</h1>
<%  end %>

<%= link_to 'Add product', new_product_path %>